export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const GET_PRODUCTS_FILTER = "GET_PRODUCTS_FILTER";
export const POST_REVIEW = "POST_REVIEW";
export const NEW_CATEGORY = "NEW_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const NEW_PRODUCT = "NEW_PRODUCT";
export const CHANGE_ORDER = "CHANGE_ORDER";
export const GET_PRODUCT = "GET_PRODUCT";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const EDIT_PRODUCT_OBTENER = "EDIT_PRODUCT_OBTENER";
export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const GET_STATES = "GET_STATES";
export const NEW_STATE = "NEW_STATE";
export const EDIT_STATE = "EDIT_STATE";
export const DELETE_STATE = "DELETE_STATE";
export const ORDERS_SHOW = "ORDERS_SHOW";
export const DISABLE_PRODUCT= "DISABLE_PRODUCT";
export const CHANGE_CART_USER = "CHANGE_CART_USER";
export const CHANGE_PROFILE = "CHANGE_PROFILE";
export const CART_SHOW = "CART_SHOW";
export const VIEW_ROLES = "VIEW_ROLES";
export const CHANGE_USER = "CHANGE_USER";
export const CONFIRM_PURCHASE = 'CONFIRM_PURCHASE';
export const SHOW_PURCHASES = 'SHOW_PURCHASES';
export const GET_ORDER = "GET_ORDER";
export const GET_ALL_PAYMENTS = "GET_ALL_PAYMENTS";

// SHOPPING CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PRODUCT_QUANTITY = "PRODUCT_QUANTITY";
export const ADD_TO_CART_DETAIL = "ADD_TO_CART_DETAIL";
export const RESET_CART = "RESET_CART";

// FAVORITE
export const ADD_TO_FAVORITE = "ADD_TO_FAVORITE";
export const ADD_TO_FAVORITE_USER = "ADD_TO_FAVORITE_USER";
export const REMOVE_FROM_FAVORITE = "REMOVE_FROM_FAVORITE";
export const FAVORITE_SHOW = "FAVORITE_SHOW";
export const RESET_FAVORITE = "RESET_FAVORITE";

