export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const GET_PRODUCTS_FILTER = "GET_PRODUCTS_FILTER";
export const POST_REVIEW = "POST_REVIEW";
export const NEW_CATEGORY = "NEW_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const NEW_PRODUCT = "NEW_PRODUCT";
export const CHANGE_ORDER = "CHANGE_ORDER";
export const GET_PRODUCT = "GET_PRODUCT";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const EDIT_CATEGORY = "EDIT_CATEGORY";
export const EDIT_PRODUCT_OBTENER = "EDIT_PRODUCT_OBTENER";
export const EDIT_PRODUCT = "EDIT_PRODUCT";

// SHOPPING CART
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const PRODUCT_QUANTITY = "PRODUCT_QUANTITY";
export const ADD_TO_CART_DETAIL = "ADD_TO_CART_DETAIL";
