export const GET_PRODUCTS = "GET_PRODUCTS";
export const PRODUCT_DETAIL = "PRODUCT_DETAIL";
export const GET_PRODUCTS_FILTER = "GET_PRODUCTS_FILTER";
export const POST_REVIEW = "POST_REVIEW";
export const NEW_CATEGORY = "NEW_CATEGORY";
export const GET_CATEGORIES = "GET_CATEGORIES";
